load('../Tiltfile', 'knative_install', 'knative_yaml')

# knative extension increases default timeout to 5 mins
# because it's slow to tear down; in CI, where we're
# often more resource constrained, that's still too slow
# sometimes
update_settings(k8s_upsert_timeout_secs=60 * 7)

knative_install('v1.8.0')

knative_yaml('service.yaml')
k8s_resource('example-html',
             port_forwards=8000)
docker_build('example-html-image', '.', live_update=[
  sync('.', '/app'),
])
