load('../Tiltfile', 'configmap_create')

configmap_create('job-config', from_file='my-job.ini=./my-job.ini')
k8s_yaml('job.yaml')

configmap_create('env-job-config', from_env_file='my-job.env')
k8s_yaml()