load('../Tiltfile', 'docker_build_sub')

k8s_yaml('deployment.yaml')
k8s_resource('example-html', port_forwards=[8000])

# Add a live_update rule to our docker_build.
docker_build_sub(
  'example-html-image',
  '.',
  dockerfile='./Dockerfile',
  extra_cmds=[
    'WORKDIR /app',
    'ADD . .',
    'ENTRYPOINT ./main.sh',
  ])
