load('../Tiltfile', 'display_dependencies')

'''
Set up dependency tree
a <—— b
 ^————^—— c <—— d
'''

k8s_yaml('a.yaml')
k8s_resource('a')

k8s_yaml('b.yaml')
k8s_resource('b', resource_deps=['a'])

k8s_yaml('c.yaml')
k8s_resource('c', resource_deps=['a', 'b'])

k8s_yaml('d.yaml')
k8s_resource('d', resource_deps=['c'])

display_dependencies()
