load('../Tiltfile', 'docker_build_with_restart')

k8s_yaml('test-job.yaml')
k8s_yaml('failing-job.yaml')

docker_build_with_restart('test_job', '.', dockerfile='Dockerfile.test', entrypoint='/start.sh',
                          live_update=[sync('./start.sh', '/start.sh')])

docker_build_with_restart('failing_job', '.', dockerfile='Dockerfile.failing', entrypoint='/fail.sh',
                          live_update=[sync('./fail.sh', '/fail.sh')])
