load('../Tiltfile', 'dotenv')

dotenv(fn='.env')
os.putenv('COMPOSE_PROJECT_NAME', 'redmine-api-dev')

expected_variables = {
    'TESTVAR': 'success',
    'THIRD': 'a = b',
    "ENV_VAR_WITH_QUOTES_1": " quotes 'and' spaces       ",
    "ENV_VAR_WITH_QUOTES_2": ' quotes "and" spaces       ',
    "ENV_VAR_WITH_QUOTES_3": " mixed 'quotes' \"and\" spaces       ",
    "ENV_VAR_WITH_QUOTES_4": "\" value with non-matching quote characters and trailing spaces   '"
}

unexpected_variables = [
    "#COMMENTED_VARNAME",
]

for key, value in expected_variables.items():
    if os.getenv(key) != value:
        fail("env variable '%s' with unexpected value. Expected '%s'" % (key, value))

for key in unexpected_variables:
    if os.getenv(key) != None:
        fail("env variable '%s' is set, but it shouldn't" % key)

local_resource(
    'echo-env-vars',
    'echo "All expected env vars are set correctly!"',
)
