load('../Tiltfile',
     'secret_create_generic',
     'secret_from_dict',
     'secret_create_docker_registry',
     'secret_create_docker_registry_ecr')

k8s_yaml(secret_from_dict("secrets", inputs = {
    'SOME_TOKEN' : os.getenv('SOME_TOKEN')
}))
secret_create_generic('pgpass', namespace='default', from_file='.pgpass=./.pgpass')
k8s_yaml('job.yaml')

secret_create_docker_registry(
    'docker-creds', username='fake-user', password='fake-password')

# Uncomment this to test ECR
#secret_create_docker_registry_ecr('ecr-creds')
