# Some common test configurations to easily get up and running with Tilt for Tests
# (see docs: https://docs.tilt.dev/tests_in_tilt.html)


def test_go(name, package, deps, timeout='', tags=None, mod='', recursive=False):
    if recursive and not package.endswith('...'):
        package = package.rstrip('/')
        package = package + '/...'

    timeout_str = ''
    if timeout:  # expects a go-parsable dur
        timeout_str = '-timeout {}'.format(timeout)
    tags_str = ''
    if tags:
        tags_str = '-tags {}'.format(','.join(tags))

    mod_str = ''
    if mod:
        mod_str = '-mod {}'.format(mod)

    cmd = 'go test {mod_str} {tags_str} {timeout_str} {path}'.format(
        mod_str=mod_str, tags_str=tags_str, timeout_str=timeout_str, path=package)
    test(name, cmd, deps=deps)
