os.putenv('TILT_HELM_REMOTE_CACHE_DIR', os.path.abspath('./.helm'))
load('../Tiltfile', 'helm_remote')

# Note that .helm is in the .tiltignore!
helm_remote('hello-world', repo_url='https://helm.github.io/examples')
if not os.path.exists('./.helm/hello-world'):
  fail('memcached failed to load in the right directory')

docker_build('helm-remote-test-verify', '.')
k8s_yaml('job.yaml')
k8s_resource('helm-remote-test-verify', resource_deps=['hello-world'])

chart_version = '25.1.0'
helm_remote('prometheus',
            repo_url='oci://ghcr.io/prometheus-community/charts',
            version=chart_version)
if not os.path.exists('./.helm/oci/ghcr.io/prometheus-community/charts/%s/prometheus' % chart_version):
  fail('prometheus failed to load in the right directory')
