# original from https://gist.github.com/angstwad/bf22d1822c38a92ec0a9
def dict_merge(dct, merge_dct):
    if not dct or not merge_dct:
        return
    for k, v in merge_dct.items():
        if k in dct and type(dct[k]) == 'dict' and type(merge_dct[k]) == 'dict':
            dict_merge(dct[k], merge_dct[k])
        else:
            dct[k] = merge_dct[k]
