FROM node:18-alpine
WORKDIR /app

COPY ./app ./
RUN npm ci
RUN echo "new image"

CMD [ \
  "npx", "nodemon", \
  "--verbose", \
  "--watch", ".", \
  "--ext", "js" , \
  "--signal", "SIGHUP", \
  "--inspect", \
  "index.js" \
]